import { Advisor, Category } from './types';

export const TRANSLATIONS = {
  en: {
    app_name: "Liuzi Tree Hollow",
    advisors_link: "Mentors",
    horoscopes_link: "Daily Mood",
    articles_link: "Stories",
    about_link: "About Us",
    login: "Log In",
    logout: "Log Out",
    signup: "Sign Up",
    hero_title: "Secrets in the Hollow, Destiny in the Cards.",
    hero_subtitle: "The exclusive emotional sanctuary for international students. From long-distance struggles to unspoken crushes, connect with expert diviners to turn your secrets into romantic guidance.",
    search_placeholder: "Search for a listener or topic...",
    ai_cta_title: "Feeling overwhelmed?",
    ai_cta_desc: "Let our Tree Hollow Guardian find the perfect listener for you.",
    ai_cta_btn: "Talk to Guardian",
    top_rated: "Warmest Listeners",
    experts: "Mentors",
    advisors_available: "listeners online",
    no_results: "No listeners found matching your criteria.",
    clear_filters: "Clear Filters",
    footer_text: "A safe space for every overseas student to share their secrets and find guidance.",
    discover: "Discover",
    support: "Support",
    download: "Download App",
    admin_portal: "Admin Portal",
    chat: "Chat",
    call: "Call",
    online: "Online",
    offline: "Offline",
    min: "min",
    rate: "Rate",
    experience: "Experience",
    reviews: "Reviews",
    years: "Years",
    chat_now: "Chat Now",
    call_now: "Call Now",
    about_me: "My Story",
    specialties: "Topics",
    credentials: "Background",
    recent_reviews: "Warm Comments",
    no_reviews: "No comments yet.",
    admin_title: "Tree Hollow Admin",
    exit_admin: "Exit to Hollow",
    manage_advisors: "Manage Listeners",
    manage_categories: "Manage Topics",
    add_advisor: "Add Listener",
    add_category: "Add Topic",
    profile: "Profile",
    name_title: "Name & Tag",
    category: "Category",
    actions: "Actions",
    create_profile: "Create Profile",
    editing: "Editing",
    display_name: "Display Name",
    display_name_zh: "Display Name (Chinese)",
    professional_title: "Role/Tagline",
    professional_title_zh: "Role/Tagline (Chinese)",
    price_per_min: "Price per Minute ($)",
    avatar_url: "Avatar Image",
    biography: "Intro",
    biography_zh: "Intro (Chinese)",
    specialties_label: "Tags (Comma separated)",
    specialties_label_zh: "Tags (Chinese, Comma separated)",
    save: "Save Changes",
    cancel: "Cancel",
    add_url: "Add URL",
    switch_lang: "中",
    // New Translations
    balance: "Balance",
    recharge: "Top Up",
    login_title: "Welcome Home",
    email_placeholder: "Email Address",
    password_placeholder: "Password",
    login_google: "Continue with Google",
    login_email: "Log In with Email",
    payment_title: "Bind Card & Add Credits",
    card_name: "Name on Card",
    card_number: "Card Number",
    expiry: "MM/YY",
    cvc: "CVC",
    pay_now: "Bind & Pay",
    insufficient_funds: "Insufficient funds. Please recharge.",
    session_active: "Session Active",
    duration: "Duration",
    cost: "Cost",
    end_session: "End Session",
    session_ended: "Session Ended",
    session_summary: "Session Summary",
    // OTP Specific
    tab_password: "Password Login",
    tab_otp: "Code Login/Reg",
    send_code: "Get Code",
    code_placeholder: "Verification Code",
    code_sent: "Sent",
    resend_in: "Resend in",
    login_register: "Login / Register",
    enter_valid_email: "Please enter a valid email.",
    enter_valid_code: "Please enter the code.",
    code_alert: "Your verification code is: 123456",
    // Daily Limit & Payment
    free_msgs_left: "Free messages left today:",
    limit_reached: "Daily free limit reached.",
    bind_card_prompt: "Please bind a credit card to continue.",
    voice_pay_prompt: "Voice calls require a linked payment method.",
    // Booking QR Modal
    scan_to_book: "Scan to Connect",
    booking_desc: "Please scan the QR code below to add our customer service for appointments.",
    qr_url_label: "Booking QR Image",
    contact_cs: "Contact CS",
    // Categories Admin
    cat_name_en: "Category Name (English)",
    cat_name_zh: "Category Name (Chinese)",
    delete_cat_confirm: "Delete this category?",
    staff_login: "Staff Login"
  },
  zh: {
    app_name: "留子树洞",
    advisors_link: "树洞倾听者",
    horoscopes_link: "每日心情",
    articles_link: "留子故事",
    about_link: "关于我们",
    login: "登录",
    logout: "退出登录",
    signup: "注册",
    hero_title: "树洞藏秘密，神谕断情关。",
    hero_subtitle: "留子专属的情感避风港。无论是异地恋的煎熬、无法言说的Crush、还是深夜的孤独，连线懂你的玄学导师，将异乡秘密化为指引情路的答案。",
    search_placeholder: "搜索倾听者或话题...",
    ai_cta_title: "有些话不知对谁说？",
    ai_cta_desc: "让树洞守护者（AI）为您匹配最懂你的倾听者。",
    ai_cta_btn: "咨询守护者",
    top_rated: "暖心倾听者",
    experts: "专家",
    advisors_available: "位倾听者在线",
    no_results: "未找到符合条件的倾听者。",
    clear_filters: "清除筛选",
    footer_text: "为每一位海外学子提供温暖的避风港，分享秘密，寻找指引。",
    discover: "探索",
    support: "支持",
    download: "下载应用",
    admin_portal: "管理后台",
    chat: "聊天",
    call: "通话",
    online: "在线",
    offline: "离线",
    min: "分钟",
    rate: "费率",
    experience: "经验",
    reviews: "评价",
    years: "年",
    chat_now: "立即倾诉",
    call_now: "立即通话",
    about_me: "关于我",
    specialties: "擅长话题",
    credentials: "背景认证",
    recent_reviews: "最新暖评",
    no_reviews: "暂无评价。",
    admin_title: "留子树洞管理后台",
    exit_admin: "返回树洞",
    manage_advisors: "倾听者管理",
    manage_categories: "话题管理",
    add_advisor: "添加倾听者",
    add_category: "添加话题",
    profile: "资料",
    name_title: "昵称与标签",
    category: "话题分类",
    actions: "操作",
    create_profile: "创建新资料",
    editing: "编辑中",
    display_name: "显示昵称",
    display_name_zh: "显示昵称 (中文)",
    professional_title: "角色/标签",
    professional_title_zh: "角色/标签 (中文)",
    price_per_min: "每分钟价格 ($)",
    avatar_url: "头像图片",
    biography: "个人简介",
    biography_zh: "个人简介 (中文)",
    specialties_label: "擅长话题 (逗号分隔)",
    specialties_label_zh: "擅长话题 (中文，逗号分隔)",
    save: "保存更改",
    cancel: "取消",
    add_url: "添加链接",
    switch_lang: "En",
    // New Translations
    balance: "余额",
    recharge: "充值",
    login_title: "欢迎回家",
    email_placeholder: "电子邮箱",
    password_placeholder: "密码",
    login_google: "使用 Google 登录",
    login_email: "使用邮箱登录",
    payment_title: "绑定银行卡并充值",
    card_name: "持卡人姓名",
    card_number: "卡号",
    expiry: "有效期",
    cvc: "安全码",
    pay_now: "绑定并支付",
    insufficient_funds: "余额不足，请充值。",
    session_active: "倾听进行中",
    duration: "时长",
    cost: "消费",
    end_session: "结束对话",
    session_ended: "对话结束",
    session_summary: "对话总结",
    // OTP Specific
    tab_password: "密码登录",
    tab_otp: "验证码登录/注册",
    send_code: "获取验证码",
    code_placeholder: "验证码",
    code_sent: "已发送",
    resend_in: "重新发送",
    login_register: "登录 / 注册",
    enter_valid_email: "请输入有效的邮箱地址。",
    enter_valid_code: "请输入验证码。",
    code_alert: "您的验证码是：123456",
    // Daily Limit & Payment
    free_msgs_left: "今日剩余免费私信：",
    limit_reached: "今日免费私信已用完。",
    bind_card_prompt: "请绑定信用卡以继续。",
    voice_pay_prompt: "语音通话需要先绑定支付方式。",
    // Booking QR Modal
    scan_to_book: "扫码连接",
    booking_desc: "请扫描下方二维码添加客服，进行后续预约服务。",
    qr_url_label: "预约二维码图片",
    contact_cs: "联系客服",
    // Categories Admin
    cat_name_en: "分类名称 (英文)",
    cat_name_zh: "分类名称 (中文)",
    delete_cat_confirm: "确定要删除此分类吗？",
    staff_login: "员工登录 (管理后台)"
  }
};

// Initial Data for Categories
export const INITIAL_CATEGORIES: Category[] = [
  { id: 'study', name: 'Academic Stress', name_zh: '学业压力' },
  { id: 'love', name: 'Relationship Advice', name_zh: '恋爱/情感' },
  { id: 'career', name: 'Career Planning', name_zh: '求职/职业' },
  { id: 'life', name: 'Life Abroad', name_zh: '海外生活' },
  { id: 'tarot', name: 'Tarot Guidance', name_zh: '塔罗指引' },
  { id: 'vent', name: 'Just Venting', name_zh: '纯吐槽' }
];

// NOTE: Since this app uses LocalStorage (no backend database),
// users who visit your deployed link will start with THIS list.
export const MOCK_ADVISORS: Advisor[] = [
  {
    id: '1',
    name: 'Sister Sarah',
    name_zh: '知心莎拉姐',
    title: 'Senior International Student',
    title_zh: '资深留英学姐',
    category: 'Life Abroad',
    imageUrl: 'https://picsum.photos/id/338/300/300',
    rating: 4.9,
    reviewCount: 1240,
    pricePerMinute: 2.99,
    isOnline: true,
    specialties: ['UK Living', 'Homesickness', 'Cooking'],
    specialties_zh: ['英国生活', '思乡缓解', '留学生做饭'],
    yearsExperience: 5,
    certificates: [
        'https://picsum.photos/id/1/400/300'
    ],
    bio: 'Been there, done that. I know how lonely it can get in a rainy city. I am here to listen and share my survival tips.',
    bio_zh: '过来人。我知道在阴雨连绵的城市里有多孤独。我在这里听你倾诉，分享我的生存技巧。',
    reviews: [
      { id: 'r1', user: 'Mike T.', rating: 5, comment: 'Really helped me calm down before exams.', date: '2023-10-12' }
    ],
    bookingQrUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=ContactAdvisor1'
  },
  {
    id: '2',
    name: 'Tarot Master Chen',
    name_zh: '陈师傅塔罗',
    title: 'Spiritual Guide',
    title_zh: '灵性指引者',
    category: 'Tarot Guidance',
    imageUrl: 'https://picsum.photos/id/1005/300/300',
    rating: 4.7,
    reviewCount: 850,
    pricePerMinute: 3.50,
    isOnline: true,
    specialties: ['Love Tarot', 'Decision Making'],
    specialties_zh: ['爱情塔罗', '选择困难'],
    yearsExperience: 8,
    certificates: ['https://picsum.photos/id/3/400/300'],
    bio: 'Using Tarot to help you find direction when you feel lost abroad.',
    bio_zh: '当你身在海外感到迷茫时，用塔罗为你指引方向。',
    reviews: [],
    bookingQrUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=ContactAdvisor2'
  },
  {
    id: '3',
    name: 'Career Coach David',
    name_zh: '大卫职业规划',
    title: 'HR Expert',
    title_zh: '前大厂HR',
    category: 'Career Planning',
    imageUrl: 'https://picsum.photos/id/64/300/300',
    rating: 5.0,
    reviewCount: 310,
    pricePerMinute: 5.99,
    isOnline: false,
    specialties: ['Resume check', 'Interview prep', 'Visa policies'],
    specialties_zh: ['简历修改', '面试辅导', '工签政策'],
    yearsExperience: 10,
    certificates: [],
    bio: 'Helping international students land their dream offers.',
    bio_zh: '帮助留学生拿下心仪的Offer。',
    reviews: [],
    bookingQrUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=ContactAdvisor3'
  }
];